name: blastapp
description: your password safe and sound
publish_to: "none"
version: 0.1.0
homepage: https://github.com/nicolgit/blast

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  kt_dart: ^1.1.0
  flutter:
    sdk: flutter
  blastmodel:
    path: ./../blastmodel
  provider: ^6.0.5
  auto_route: ^10.1.0+1
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  diacritic: ^0.1.5
  humanizer: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  multi_select_flutter: ^4.1.3
  oauth2: ^2.0.2
  app_links: ^6.1.0
  loader_overlay: ^5.0.0
  win32_registry: ^2.1.0
  file_picker: ^10.2.0
  intl: ^0.20.2
  flutter_window_close: ^1.0.0
  flutter_platform_alert: ^0.8.0
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  mask_text_input_formatter: ^2.9.0
  window_manager: ^0.5.0
  biometric_storage: ^5.0.1
  lottie: ^3.1.2
  printing: ^5.14.2
  flutter_markdown: ^0.7.4+1
  markdown_widget: ^2.3.2+8

flutter_launcher_icons:
  image_path: "assets/general/app-icon.png"
  remove_alpha_ios: true
  android: "launcher_icon"
  ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 128 # min:48, max:256, default: 48
  macos:
    generate: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.12
  msix: ^3.16.9

flutter:
  uses-material-design: true
  assets:
    - assets/general/
    - assets/storage/

msix_config:
  display_name: blast open source password manager
  publisher_display_name: Rubber Duckies farm
  identity_name: RubberDuckiesfarm.blastopensourcepasswordmanager
  publisher: CN=4CCF9CCB-473B-4745-A9F5-E48C2703FA41
  logo_path: assets/general/app-icon.png
  store: true
