name: blastapp
description: your password safe and sound
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  kt_dart: ^1.1.0
  flutter:
    sdk: flutter
  viewmodelpackage:
    path: ./../viewmodelpackage
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
