name: blastapp
description: your password safe and sound
publish_to: 'none'
version: 0.1.0
homepage: https://github.com/nicolgit/blast

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  kt_dart: ^1.1.0
  flutter:
    sdk: flutter
  blastmodel:
    path: ./../blastmodel
  provider: ^6.0.5
  auto_route: ^9.2.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  diacritic: ^0.1.5
  humanizer: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  multi_select_flutter: ^4.1.3
  oauth2: ^2.0.2
  app_links: ^6.1.0
  loader_overlay: ^4.0.0
  win32_registry: ^1.1.2
  file_picker: ^8.0.0+1
  intl: ^0.19.0
  flutter_window_close: ^1.0.0
  flutter_platform_alert: ^0.6.1
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  mask_text_input_formatter: ^2.9.0
  desktop_window: ^0.4.2

flutter_launcher_icons:
 image_path: "assets/general/app-icon.png"
 android: true
 ios: true
 web:
    generate: true
    image_path: "assets/general/app-icon.png"
 windows:
    generate: true
    image_path: "assets/general/app-icon.png"
    icon_size: 128 # min:48, max:256, default: 48
 macos:
    generate: true
    image_path: "assets/general/app-icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/general/
    - assets/storage/