name: blastapp
description: your password safe and sound
publish_to: 'none'
version: 0.1.0
homepage: https://github.com/nicolgit/blast

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  kt_dart: ^1.1.0
  flutter:
    sdk: flutter
  blastmodel:
    path: ./../blastmodel
  provider: ^6.0.5
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
