name: web (purple-flower)

on: workflow_dispatch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # checkout the code
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      # setup flutter
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.2
      - name: Prepare secrets.dart
        working-directory: ./code/app/blastmodel/lib
        run: |
          cp secretsToFill.dart secrets.dart
          build=$(date +%Y.%m.%d).web
          sed -i 's/class SecretsToFill/class Secrets/g' secrets.dart
          sed -i 's/ONEDRIVE_APPLICATION_ID/${{ secrets.ONEDRIVE_APPLICATION_ID }}/g' secrets.dart
          sed -i "s/BUILD_NUMBER/$build/g" secrets.dart
          cat secrets.dart

      # Create badge
      # https://github.com/marketplace/actions/bring-your-own-badge
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          name: webtime
          label: 'Updated at'
          status: $build
          color: 101010
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      # Install packages
      - name: Install packages
        working-directory: ./code/app/blastapp
        run: |
          flutter config --enable-web
          flutter pub upgrade
          flutter pub get
          flutter build web --release
      
      # Build and deploy
      # https://github.com/marketplace/actions/azure-static-web-apps-deploy
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FLOWER_03FFD151E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/code/app/blastapp/build/web" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/code/app/blastapp/build/web" # Built app content directory - optional
          # app_build_command: 'flutter build web'
          ###### End of Repository/Build Configurations ######
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FLOWER_03FFD151E }}
          action: "close"
