name: deploy to web (purple-flower)

on: workflow_dispatch
env:
  MYBUILD: empty
  
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # checkout the code
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      

      - name: variables
        working-directory: ./code/app/blastmodel/lib
        run: |
          build=$(date +%Y.%m.%d).$(date +%H%M)
          echo 'MYBUILD='$build >> $GITHUB_ENV

          cp secretsToFill.dart secrets.dart
          sed -i 's/class SecretsToFill/class Secrets/g' secrets.dart
          sed -i 's/ONEDRIVE_APPLICATION_ID/${{ secrets.ONEDRIVE_APPLICATION_ID }}/g' secrets.dart
          sed -i "s/BUILD_NUMBER/$build/g" secrets.dart
          cat secrets.dart

      # setup flutter
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.6
      
      
      # build
      - name: build flutter app
        working-directory: ./code/app/blastapp
        run: |
          flutter config --enable-web
          flutter pub upgrade
          flutter pub get
          flutter build web --release
      
      # deploy to static web app
      # https://github.com/marketplace/actions/azure-static-web-apps-deploy
      - name: deploy to static web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FLOWER_03FFD151E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/code/app/blastapp/build/web" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/code/app/blastapp/build/web" # Built app content directory - optional
          # app_build_command: 'flutter build web'
          ###### End of Repository/Build Configurations ######

      # https://github.com/marketplace/actions/build-a-badge
      - name: build read.me badge
        uses: peterrhodesdev/build-a-badge@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: badge-web
          label: latest build
          message: ${{ env.MYBUILD }}
  

