name: deploy-to-windows-store
on: workflow_dispatch

jobs:
  build_and_deploy_job:
    runs-on: windows-latest
    name: Build and Deploy Job
    steps:
      # checkout the code
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      # setup flutter
      # https://github.com/marketplace/actions/flutter-action
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#          flutter-version: 3.27.2
      
#      - name: Prepare secrets.dart
#        working-directory: ./code/app/blastmodel/lib
#        run: |
#          cp secretsToFill.dart secrets.dart
#          build=$(date +%Y.%m.%d).web
#          sed -i 's/class SecretsToFill/class Secrets/g' secrets.dart
#          sed -i 's/ONEDRIVE_APPLICATION_ID/${{ secrets.ONEDRIVE_APPLICATION_ID }}/g' secrets.dart
#          sed -i "s/BUILD_NUMBER/$build/g" secrets.dart
#          cat secrets.dart

      # Step 3: Run the PowerShell script
      - name: Run PowerShell commands
        working-directory: ./code/app/blastmodel/lib
        shell: pwsh
        run: |
          Copy-Item -Path "secretsToFill.dart" -Destination "secrets.dart"
          $build = (Get-Date -Format "yyyy.MM.dd") + ".web"
          (Get-Content -Path "secrets.dart") -replace 'class SecretsToFill', 'class Secrets' | Set-Content -Path "secrets.dart"
          (Get-Content -Path "secrets.dart") -replace 'ONEDRIVE_APPLICATION_ID', '${{ secrets.ONEDRIVE_APPLICATION_ID }}' | Set-Content -Path "secrets.dart"
          (Get-Content -Path "secrets.dart") -replace 'BUILD_NUMBER', $build | Set-Content -Path "secrets.dart"
          Get-Content -Path "secrets.dart"

      - name: build time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: windowdbuild
          LABEL: 'latest build'
          STATUS: $build
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


