name: deploy-to-windows-store
on: workflow_dispatch

jobs:
  build_and_deploy_job:
    runs-on: windows-latest
    name: Build and Deploy Job
    steps:
      # checkout the code
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      # setup flutter
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.2
      - name: Prepare secrets.dart
        working-directory: ./code/app/blastmodel/lib
        run: |
          cp secretsToFill.dart secrets.dart
          build=$(date +%Y.%m.%d).web
          sed -i 's/class SecretsToFill/class Secrets/g' secrets.dart
          sed -i 's/ONEDRIVE_APPLICATION_ID/${{ secrets.ONEDRIVE_APPLICATION_ID }}/g' secrets.dart
          sed -i "s/BUILD_NUMBER/$build/g" secrets.dart
          cat secrets.dart

      # Create badge
      # https://github.com/marketplace/actions/bring-your-own-badge
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          name: webtime
          label: 'Updated at'
          status: $build
          color: 101010
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      # Install packages
      - name: Install packages
        working-directory: ./code/app/blastapp
        run: |
          flutter config --enable-web
          flutter pub upgrade
          flutter pub get
          flutter build web --release
      
