name: deploy-to-windows-store
on: workflow_dispatch

env:
  MYBUILD: empty
  
jobs:
  build_and_deploy_job:
    runs-on: windows-latest
    name: Build and Deploy Job
    steps:
      # checkout the code
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      # Step 3: Run the PowerShell script
      - name: prepare variables
        working-directory: ./code/app/blastmodel/lib
        shell: pwsh
        run: |
          $build = (Get-Date -Format "yyyy.MM.dd") + ".web"
          echo "MYBUILD=$build" >> $env:GITHUB_ENV
          
          Copy-Item -Path "secretsToFill.dart" -Destination "secrets.dart"
          (Get-Content -Path "secrets.dart") -replace 'class SecretsToFill', 'class Secrets' | Set-Content -Path "secrets.dart"
          (Get-Content -Path "secrets.dart") -replace 'ONEDRIVE_APPLICATION_ID', '${{ secrets.ONEDRIVE_APPLICATION_ID }}' | Set-Content -Path "secrets.dart"
          (Get-Content -Path "secrets.dart") -replace 'BUILD_NUMBER', $build | Set-Content -Path "secrets.dart"
          Get-Content -Path "secrets.dart"

      # setup flutter
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # build app
      - name: build app
        working-directory: ./code/app/blastapp
        run: |
          flutter config --enable-web
          flutter pub upgrade
          flutter pub get
          flutter build windows --release

      # https://github.com/marketplace/actions/build-a-badge
      - name: build read.me badge
        uses: peterrhodesdev/build-a-badge@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: badge-windows
          label: latest build
          message: ${{ env.MYBUILD }}

